social/groups/urls.py
from django.urls import path
from .views import (CreateGroupView, ListGroupsView, SingleGroupView,
                    JoinGroupView, LeaveGroupView, UserGroupsView)


app_name = 'groups'
urlpatterns = [
    path('', ListGroupsView.as_view(), name='all'),
    path('<str:username>', UserGroupsView.as_view(), name='user_groups'),
    path('<slug>/$/', SingleGroupView.as_view(), name='single'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path('<slug>/$/join/', JoinGroupView.as_view(), name='join_group'),
    path('<slug>/$/leave/', LeaveGroupView.as_view(), name='leave_group'),
]

social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('by/<str:username>/edit', views.EditProfileView.as_view(), name='edit_profile'),
    path('by/<str:username>/<int:pk>', views.PostDetailView.as_view(), name='single'),
    path('by/<str:username>/<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),
]

social/social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html',
                                          redirect_authenticated_user=True),
                                          name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('threads/', include('groups.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/groups/models.py
from django.db import models
import misaka
from django.urls import reverse
from django.utils.text import slugify

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(verbose_name='Thread name', unique=True, max_length=255)
    slug = models.SlugField(unique=True, allow_unicode=True)
    description = models.TextField(default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        Completes the attribures 'slug' and 'description_html' and saves the group to a database
        """
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """
        Built-in django method that compiles a URL for a created group.
        """
        return reverse('groups:single', kwargs={'slug': self.slug})


class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='membership')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

social/groups/forms.py
from django import forms
from django.core import validators

from .models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'rows': 3})

social/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Group, GroupMember
from .forms import CreateGroupForm
from accounts.models import User


# Create your views here.

class CreateGroupView(LoginRequiredMixin, generic.CreateView):
    """
    Renders form to create new thread
    """
    login_url = 'home'
    model = Group
    form_class = CreateGroupForm


class SingleGroupView(generic.DetailView):
    """
    Renders thread details
    """
    model = Group


class ListGroupsView(generic.ListView):
    """
    Renders a list of all threads ordered by total num of posts and users in a descending order
    """
    model = Group

    def get_queryset(self):
        queryset = Group.objects.annotate(number_of_posts=Count('posts'),
                                          number_of_members=Count('members'))
        return queryset.order_by('-number_of_posts', '-number_of_members')


class UserGroupsView(generic.ListView):
    """
    Renders a list of groups joined by an owner of a profile page
    """
    model = Group
    template_name = 'groups/user_groups.html'


    def get_context_data(self, **kwargs):
        self.post_user = get_object_or_404(User, username__iexact=self.kwargs.get('username'))
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        context['user_groups'] = Group.objects.filter(members__in=[self.post_user]).order_by('name')
        return context


class JoinGroupView(LoginRequiredMixin, generic.RedirectView):
    """
    A view to join a thread
    """
    login_url = 'home'

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'You are already a member of this group!')
        else:
            messages.success(self.request, 'Congratulations! You joined a group.')
        return super().get(request, *args, **kwargs)


class LeaveGroupView(LoginRequiredMixin, generic.RedirectView):
    """
    A view to leave a thread
    """
    def get_redirect_url(self, *args, **kwargs):
        print(self.kwargs)
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
            print(f'membership={membership}')  # TO BE DELETED
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'You are not a member of a group')
        else:
            membership.delete()
            messages.success(self.request, 'You left a group.')
        return super().get(request, *args, **kwargs)

social/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
      {% block pregroup %}{% endblock %}
      {% block group_content %}{% endblock %}
      {% block postgroup %}{% endblock %}
    </div>
{% endblock %}

social/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block pregroup %}
<div class="col-lg-4 col-sm-12 pt-1">
  <div class="row">
    <div class="col-lg-9">
      <h1 class="group-heading mr-3 overpass"> {{ group.name }} </h1>
    </div>
    <div class="col-lg-3 mt-2 pr-0">
      {% if user in group.members.all %}
        <a href="{% url 'groups:leave_group' slug=group.slug%}"
        class="btn btn-outline-primary align-self-center ">
        <span class="fas fa-user-minus mini"></span><small>Leave</small></a>
      {% else %}
        <a href="{% url 'groups:join_group' slug=group.slug%}"
        class="btn btn-main-action align-self-center ">
        <span class="fas fa-user-plus mini icon"></span><small>Join</small></a>
      {% endif %}
    </div>
  </div>
  <p><span class="fas fa-user-friends icon"></span>{{ group.members.count }}</p>
  <p class="text-justify">{{group.description|safe|linebreaksbr}}</p>
</div>
{% endblock %}

{% block group_content %}
  <div class="col-md-6 pt-1">
  {% for post in group.posts.all %}
    {% include 'posts/_post.html' %}
    </div></div>
  {% empty %}
    <h2>No posts yet</h2>
  {% endfor %}
  </div>
{% endblock %}

social/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}


{% block pregroup %}
  <div class="col-md-6">
    <h2 class="overpass mb-4">Create new thread</h2>
      <form class="regform" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-main-action" value="Create Thread">
      </form>
  </div>
{% endblock %}

social/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="col-md-8 threads">
  <div class="mb-3">
    <h1 class="overpass mb-1">Popular Threads</h1>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create_group' %}" class="btn btn-new-group">
      New Thread</a>
    {% endif %}
  </div>
{% endblock %}


{% block group_content %}
  {% for group in group_list  %}
    <div class="group-card">
      <a href="{% url 'groups:single' slug=group.slug %}">
        <h2 class="list-group-title"> <span class="fas fa-users icon">
        </span> {{ group.name }} </h2>
      </a>
      <div class="list-group-item-text">
        {{ group.description_html|safe|linebreaksbr }}
        <div class="row">
          <div class="col-lg-3 col-xs-12">
            <span class="badge badge-pill badge-secondary"> {{group.members.count}}</span>
            <small>member{{group.members.count|pluralize}}</small>

          </div>

          <div class="col-lg-2 col-xs-12">
            <span class="badge badge-pill badge-secondary"> {{group.posts.all.count}}</span>
            <small>post{{group.posts.all.count|pluralize}}</small>
          </div>
        </div>
        </div>
    </div>
  {% endfor %}


  </div>

{% endblock %}

social/groups/templates/groups/user_groups.html
{% extends "groups/group_base.html" %}
{% load static %}

{% block group_content %}
<div class="col-md-8">
  <h1 class="overpass">Threads
    <a href="{% url 'posts:user_profile' username=post_user.username %}">
      {{post_user}}</a> reads
      </h1>
  {% for group in user_groups  %}

      <a href="{% url 'groups:single' slug=group.slug %}">
        <h5 class="group-list-item"><span class="fas fa-users icon"></span>
          {{group.name}}</h5>
      </a></h5>
  {% endfor %}
</div>
{% endblock %}