social/groups/urls.py
from django.urls import path
from .views import (CreateGroupView, ListGroupsView, SingleGroupView,
                    JoinGroupView, LeaveGroupView, UserGroupsView)


app_name = 'groups'
urlpatterns = [
    path('', ListGroupsView.as_view(), name='all'),
    path('<str:username>', UserGroupsView.as_view(), name='user_groups'),
    path('<slug>/$/', SingleGroupView.as_view(), name='single'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path('<slug>/$/join/', JoinGroupView.as_view(), name='join_group'),
    path('<slug>/$/leave/', LeaveGroupView.as_view(), name='leave_group'),
]

social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('by/<str:username>/edit', views.EditProfileView.as_view(), name='edit_profile'),
    path('by/<str:username>/<int:pk>', views.PostDetailView.as_view(), name='single'),
    path('by/<str:username>/<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),
]

social/social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html',
                                          redirect_authenticated_user=True),
                                          name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('threads/', include('groups.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/posts/models.py
from django.db import models

from django.urls import reverse

from django.conf import settings

import misaka

from groups.models import Group

from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    image = models.ImageField(upload_to='images', blank=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                               'pk': self.pk})

    class Meta:
        ordering = ['-created_at']

social/posts/forms.py
from django import forms
from .models import Post


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'message', 'image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].label = 'Upload image'
        self.fields['message'].widget.attrs.update({'rows': 6})

social/posts/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from .forms import NewPostForm

from .models import Post
from groups.models import Group
from accounts.models import User

from accounts.forms import UserProfileForm
from accounts.models import UserProfile


class UserProfileView(generic.ListView):
    """
    Renders a list of posts written by currently loggined-in user
    """
    model = Post
    template_name = 'posts/user_profile.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        context['user_groups'] = Group.objects.filter(members__in=[self.post_user]).count()
        return context


class EditProfileView(LoginRequiredMixin, UpdateView):
    """
    Renders a form to edit user's profile
    """
    form_class = UserProfileForm
    template_name = 'posts/edit_profile.html'

    def get_object(self, queryset=None):
        object = get_object_or_404(UserProfile, user__username=self.kwargs.get('username'))
        return object

    def get_success_url(self):
        username = self.kwargs.get('username')
        return reverse('posts:user_profile', kwargs={'username': username})


class PostDetailView(generic.DetailView):
    """
    Renders post's details
    """
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePostView(LoginRequiredMixin, generic.CreateView):
    """
    Renders a form to create new post
    """
    form_class = NewPostForm
    template_name = 'posts/post_form.html'

    def get_success_url(self):
        group_id = self.request.POST['group']
        return reverse_lazy('groups:single', kwargs={'slug': Group.objects.get(id=group_id).slug})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin, generic.DeleteView):
    """
    Renders from to delete a post
    """
    model = Post
    select_related = ('user', 'group')

    def get_success_url(self):
        username = self.kwargs.get('username')
        return reverse_lazy('posts:user_profile', kwargs={'username': username})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

social/posts/templates/posts/_post.html
  <div class="post-body pt-1 mb-4">
    <span class="far fa-comment-alt"></span>
      <a class="ml-2 mini" href="{% url 'posts:user_profile' username=post.user.username %}">
        @{{post.user.username}}
      </a>
    <h5 class="text-justify">{{post.message_html|safe}}</h5>
    {% if post.image %}
      <img class="post-img" src="{{post.image.url}}" alt="">
    {% endif %}



    <div class="d-flex">

      <p class="mr-4 mini">
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
          {{post.created_at}}
        </a>
      </p>

social/posts/templates/posts/edit_profile.html
{% extends "posts/post_base.html" %}
{% load crispy_forms_tags %}

{% block post_content %}

<h1 class="overpass">Edit profile</h1>
<div class="col-md-6 pl-0">
  <form class="regform" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.bio|as_crispy_field}}
    {{form.profile_pic|as_crispy_field}}
    <input type="submit" class="btn btn-main-action" value="Save profile">
  </form>
</div>



{% endblock %}

social/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="posts-page">
    <div class="container">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block postpost %}{% endblock %}

    </div>
  </div>

{% endblock %}

social/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h2 class="overpass mb-5">Are you sure you want to delete this post?</h2>

<div class="col-lg-6 pl-0">
  {% include "posts/_post.html" with post=object hide_delete=True %}
  </div></div>

  <form method="post">
  {% csrf_token %}
    <input type="submit" class="btn btn-outline-light" value="Delete">
    <a class="btn btn-dark ml-1"
      href="{% url 'posts:user_profile' username=post.user.username %}">
      Cancel
    </a>
  </form>
</div>



{% endblock %}

social/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% include "posts/_post.html" %}
  </div></div>

    {% if post.user == user and user.is_authenticated %}

    <a href="{% url 'posts:delete_post' username=post.user.username pk=post.pk %}"
      class="btn btn-danger"> <span class="fas fa-times icon"></span> Delete</a>
    {% endif %}
  </div>




{% endblock %}

social/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}


{% block post_content %}
<h1 class="overpass mb-4">New post</h1>
<div class="col-md-6 pl-0">
  <form class="regform" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-main-action" type="submit">
      <span class="fas fa-paper-plane icon">
    </span>Send
  </button>
  </form>
</div>

{% endblock %}

social/posts/templates/posts/user_profile.html
{% extends "posts/post_base.html" %}
{% load static %}


{% block prepost %}
<div class="row">
  <div class="col-md-3 profile-box">
    <div class="profile-pic-box">
      {% if post_user.profile.profile_pic %}
        <img src="{{ post_user.profile.profile_pic.url }}" alt="">
      {% else %}
        <img src="{% static 'images/default-avatar.png' %}">
      {% endif %}
    </div>

    <div class="profile-info-box">
      <h1 class="overpass">@{{post_user.username}}</h1>
      <small>{{post_user.profile.bio|safe|linebreaksbr}}</small>
    </div>

    <div class="profile-threads-box">
      <a href="{% url 'groups:user_groups' username=post_user.username %}">
        My subscriptions:</a>
        <span class="badge badge-pill my-badge">{{user_groups}}</span>
    </div>

  </div>


{% endblock %}

{% block post_content %}
  <div class="col-md-6">
    {% for post in post_list  %}
     {% include "posts/_post.html" %}
     <p class="mini">
       <a href="{% url 'groups:single' slug=post.group.slug %}">
         <span class="fas fa-users icon mini"></span>
         {{post.group.name}}
       </a>
    </div></div>
    {% endfor %}
  </div>
</div>
{% endblock %}