social/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

social/groups/urls.py
from django.urls import path
from .views import (CreateGroupView, ListGroupsView, SingleGroupView,
                    JoinGroupView, LeaveGroupView, UserGroupsView)


app_name = 'groups'
urlpatterns = [
    path('', ListGroupsView.as_view(), name='all'),
    path('<str:username>', UserGroupsView.as_view(), name='user_groups'),
    path('<slug>/$/', SingleGroupView.as_view(), name='single'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path('<slug>/$/join/', JoinGroupView.as_view(), name='join_group'),
    path('<slug>/$/leave/', LeaveGroupView.as_view(), name='leave_group'),
]

social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('by/<str:username>/edit', views.EditProfileView.as_view(), name='edit_profile'),
    path('by/<str:username>/<int:pk>', views.PostDetailView.as_view(), name='single'),
    path('by/<str:username>/<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),
]

social/social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html',
                                          redirect_authenticated_user=True),
                                          name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('threads/', include('groups.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!-- Bootstrap 4.5 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

      <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Overpass&display=swap" rel="stylesheet">

    <!-- Fonts -->
    <script src="https://kit.fontawesome.com/3e9e50c803.js" crossorigin="anonymous"></script>

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <title>Social Space</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark overpass">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span class="fas fa-rocket"></span> Social Space</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNav" aria-controls="navbarNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item"><a class="btn btn-nav btn-new-post" href="{% url 'posts:create_post' %}">New post</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Threads</a></li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  @{{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item lato mini" href="{% url 'posts:user_profile' username=user.username %}">My profile</a>
                  <a class="dropdown-item lato mini" href="{% url 'posts:edit_profile' username=user.username %}">Edit profile</a>
                </div>
              </li>




              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Threads</a></li>
              <li class="nav-item"><a class="btn btn-nav btn-outline-light" href="{% url 'accounts:signup' %}">Sign Up</a>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

social/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}


{% block content %}
  <h1 class="overpass mb-4">Welcome to Social Network!</h1>

  <div class="col-md-4 pl-0">
    <form method="post" class="regform">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-main-action" value="Log in">
    </form>
    <p><a href="#">Forgot your password?</a></p>
  </div>




{% endblock %}